FROM osrf/ros:humble-desktop-full
# 安装依赖
RUN apt update && apt install -y --no-install-recommends \
    libgoogle-glog-dev libgflags-dev libcgal-dev \
    libatlas-base-dev libsuitesparse-dev libceres-dev
# 安装g2o
WORKDIR /home
RUN git clone https://github.com/RainerKuemmerle/g2o.git && \
    cd g2o && mkdir build && cd build && cmake .. && make -j8 && make install

RUN mkdir -p /home/code/colcon_ws/src
WORKDIR /home/code/colcon_ws

COPY . ./src/LifelongBackend/
# 重新编译proto文件
RUN cd ./src/LifelongBackend/lifelong_backend/proto \
    && protoc --cpp_out=. graph.proto \
    && protoc --cpp_out=. sc.proto \
    && protoc --cpp_out=. transform.proto  

RUN source /opt/ros/humble/setup.bash \
    && colcon build  --cmake-args=-DCMAKE_BUILD_TYPE=Release

